apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
spec:
  selector:
    matchLabels:
      app: service1
  replicas: 1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
      - name: service1
        image: sivasai2003/cart:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  selector:
    app: service1
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
##############service-2#######################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2
spec:
  selector:
    matchLabels:
      app: service2
  replicas: 1
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
      - name: service2
        image: sivasai2003/catalogue:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service2
spec:
  selector:
    app: service2
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
###############service-3######################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service3
spec:
  selector:
    matchLabels:
      app: service3
  replicas: 1
  template:
    metadata:
      labels:
        app: service3
    spec:
      containers:
      - name: service3
        image: sivasai2003/dispatch:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service3
spec:
  selector:
    app: service3
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
#################service-4################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service4
spec:
  selector:
    matchLabels:
      app: service4
  replicas: 1
  template:
    metadata:
      labels:
        app: service4
    spec:
      containers:
      - name: service4
        image: sivasai2003/fluentd:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service4
spec:
  selector:
    app: service4
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
################service-5################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service5
spec:
  selector:
    matchLabels:
      app: service5
  replicas: 1
  template:
    metadata:
      labels:
        app: service5
    spec:
      containers:
      - name: service5
        image: sivasai2003/loadgen:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service5
spec:
  selector:
    app: service5
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
###################service-6##############
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service6
spec:
  selector:
    matchLabels:
      app: service6
  replicas: 1
  template:
    metadata:
      labels:
        app: service6
    spec:
      containers:
      - name: service6
        image: sivasai2003/mongo:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service6
spec:
  selector:
    app: service6
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
######################service-7###################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service7
spec:
  selector:
    matchLabels:
      app: service7
  replicas: 1
  template:
    metadata:
      labels:
        app: service7
    spec:
      containers:
      - name: service7
        image: sivasai2003/mysql:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service7
spec:
  selector:
    app: service7
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
##############service-8################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service8
spec:
  selector:
    matchLabels:
      app: service8
  replicas: 1
  template:
    metadata:
      labels:
        app: service8
    spec:
      containers:
      - name: service8
        image: sivasai2003/payment:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service8
spec:
  selector:
    app: service8
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
#####################3service-9##################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service9
spec:
  selector:
    matchLabels:
      app: service9
  replicas: 1
  template:
    metadata:
      labels:
        app: service9
    spec:
      containers:
      - name: service9
        image: sivasai2003/ratings:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service9
spec:
  selector:
    app: service9
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
#################service-10###############
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service10
spec:
  selector:
    matchLabels:
      app: service10
  replicas: 1
  template:
    metadata:
      labels:
        app: service10
    spec:
      containers:
      - name: service10
        image: sivasai2003/shipping:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service10
spec:
  selector:
    app: service10
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
#################3service-11#################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service11
spec:
  selector:
    matchLabels:
      app: service11
  replicas: 1
  template:
    metadata:
      labels:
        app: service11
    spec:
      containers:
      - name: service11
        image: sivasai2003/user:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service11
spec:
  selector:
    app: service11
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
###################service-12###############
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service12
spec:
  selector:
    matchLabels:
      app: service12
  replicas: 1
  template:
    metadata:
      labels:
        app: service12
    spec:
      containers:
      - name: service12
        image: sivasai2003/web:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service12
spec:
  selector:
    app: service12
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
